---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-ms
  labels:
    app: business-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-ms
  template:
    metadata:
      labels:
        app: business-ms
    spec:
      containers:
        - name: business-ms
          image: acrpurplebcp.azurecr.io/business-ms:1.0.0
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acrpurplebcp-secret
